### 准备数据集

In [5]:
# 加载tokenizer
from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained('hfl/rbt3')

In [2]:
tokenizer

BertTokenizer(name_or_path='hfl/rbt3', vocab_size=21128, model_max_length=1000000000000000019884624838656, padding_side='right', truncation_side='right', special_tokens={'unk_token': '[UNK]', 'sep_token': '[SEP]', 'pad_token': '[PAD]', 'cls_token': '[CLS]', 'mask_token': '[MASK]'}, added_tokens_decoder={
	0: AddedToken("[PAD]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	100: AddedToken("[UNK]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	101: AddedToken("[CLS]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	102: AddedToken("[SEP]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	103: AddedToken("[MASK]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
})

In [4]:
# 试用
tokenizer(['明月装饰了你的窗子', '你装饰了别人的梦'], 
                           truncation=True)

{'input_ids': [[101, 3209, 3299, 6163, 7652, 749, 872, 4638, 4970, 2094, 102], [101, 872, 6163, 7652, 749, 1166, 782, 4638, 3457, 102]], 'token_type_ids': [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], 'attention_mask': [[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]]}

In [6]:
# 从磁盘加载中文数据集
from datasets import load_from_disk

dataset = load_from_disk('./data/ChnSentiCorp/')

In [6]:
dataset

DatasetDict({
    train: Dataset({
        features: ['text', 'label'],
        num_rows: 9600
    })
    validation: Dataset({
        features: ['text', 'label'],
        num_rows: 0
    })
    test: Dataset({
        features: ['text', 'label'],
        num_rows: 1200
    })
})

In [7]:
# 缩小数据规模, 便于测试
dataset['train'] = dataset['train'].shuffle().select(range(2000))
dataset['test'] = dataset['test'].shuffle().select(range(100))

In [9]:
dataset['train'][0]

{'text': '对比了好长时间才选择的这款，配置还是不错的，做工很精致，外观全黑很漂亮，送的赠品也不错，摄像头很清晰，.奥特蓝星音质也很好，性价比高',
 'label': 1}

In [8]:
def f(data, tokenizer):
    return tokenizer(data['text'], truncation=True)

dataset = dataset.map(f, batched=True,
                     batch_size=1000,
                     num_proc=4,
                     remove_columns=['text'],
                     fn_kwargs={'tokenizer': tokenizer})

dataset

Map (num_proc=4):   0%|          | 0/2000 [00:00<?, ? examples/s]

Map (num_proc=4):   0%|          | 0/100 [00:00<?, ? examples/s]

DatasetDict({
    train: Dataset({
        features: ['label', 'input_ids', 'token_type_ids', 'attention_mask'],
        num_rows: 2000
    })
    validation: Dataset({
        features: ['label'],
        num_rows: 0
    })
    test: Dataset({
        features: ['label', 'input_ids', 'token_type_ids', 'attention_mask'],
        num_rows: 100
    })
})

In [9]:
# 删掉太长的句子
def f(data):
    return [len(i) <= 512 for i in data['input_ids']]

dataset = dataset.filter(f, batched=True, batch_size=1000, num_proc=4)

Filter (num_proc=4):   0%|          | 0/2000 [00:00<?, ? examples/s]

Filter (num_proc=4):   0%|          | 0/100 [00:00<?, ? examples/s]

In [11]:
from transformers import AutoModelForSequenceClassification

In [12]:
model = AutoModelForSequenceClassification.from_pretrained('hfl/rbt3', num_labels=2)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Loading weights:   0%|          | 0/55 [00:00<?, ?it/s]

[transformers] BertForSequenceClassification LOAD REPORT from: hfl/rbt3
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.decoder.weight             | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
classifier.weight                          | MISSING    |
classifier.bias                            | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
Exception in thread Thread-auto_conversion:
Traceback (most recent call last):
  File "C:\ProgramData\anaconda3\Lib\site-packages\huggingface_hub\utils\_http.py", line 761, in hf_raise_for_status
    response.raise_for_status()
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\ProgramData\anaconda3\Lib\site-packages\httpx\_models.py", line 829, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Client error '403 Forbidden' for url 'https://huggingface.co/api/models/hfl/rbt3/discussions?p=0'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/403

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\ProgramData\anaconda3\Lib\threading.py", line 1043, in _bootstrap_inner
    self.run()
    ~~~~~~~~^^
  File "C:\ProgramData\anaconda3\Lib\site-packages\ipykernel\ipkernel.py", line 772, in run_closure
    _threading_Thread_run(self)
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "C:\ProgramData\anaconda3\Lib\threading.py", line 994, in run
    self._target(*self._args, **self._kwargs)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\Lib\site-packages\transformers\safetensors_conversion.py", line 117, in auto_conversion
    raise e
  File "C:\ProgramData\anaconda3\Lib\site-packages\transformers\safetensors_conversion.py", line 96, in auto_conversion
    sha = get_conversion_pr_reference(api, pretrained_model_name_or_path, **cached_file_kwargs)
  File "C:\ProgramData\anaconda3\Lib\site-packages\transformers\safetensors_conversion.py", line 69, in get_conversion_pr_reference
    pr = previous_pr(api, model_id, pr_title, token=token)
  File "C:\ProgramData\anaconda3\Lib\site-packages\transformers\safetensors_conversion.py", line 14, in previous_pr
    for discussion in get_repo_discussions(repo_id=model_id, token=token):
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\Lib\site-packages\huggingface_hub\hf_api.py", line 6954, in get_repo_discussions
    discussions, has_next = _fetch_discussion_page(page_index=page_index)
                            ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\Lib\site-packages\huggingface_hub\hf_api.py", line 6943, in _fetch_discussion_page
    hf_raise_for_status(resp)
    ~~~~~~~~~~~~~~~~~~~^^^^^^
  File "C:\ProgramData\anaconda3\Lib\site-packages\huggingface_hub\utils\_http.py", line 849, in hf_raise_for_status
    raise _format(HfHubHTTPError, message, response) from e
huggingface_hub.errors.HfHubHTTPError: (Request ID: Root=1-69f2f417-53609ddf1b87661b3225b695;2544018b-8a69-419c-a861-0e1821117d7d)

403 Forbidden: Discussions are disabled for this repo.
Cannot access content at: https://huggingface.co/api/models/hfl/rbt3/discussions?p=0.
Make sure your token has the correct permissions.

In [13]:
# 统计模型参数量
sum([i.nelement() for i in model.parameters()])

38478338

In [14]:
# 模型试算
import torch

# 模拟一条数据
data = {
    'input_ids': torch.ones(4, 10, dtype=torch.long),
    'token_type_ids': torch.ones(4, 10, dtype=torch.long),
    'attention_mask': torch.ones(4, 10, dtype=torch.long),
    'labels': torch.ones(4, dtype=torch.long)
}

out = model(**data)

In [16]:
out

SequenceClassifierOutput(loss=tensor(0.6901, grad_fn=<NllLossBackward0>), logits=tensor([[-0.0946, -0.0885],
        [-0.0946, -0.0885],
        [-0.0946, -0.0885],
        [-0.0946, -0.0885]], grad_fn=<AddmmBackward0>), hidden_states=None, attentions=None)

In [17]:
out['loss']

tensor(0.6901, grad_fn=<NllLossBackward0>)

In [18]:
out['logits']

tensor([[-0.0946, -0.0885],
        [-0.0946, -0.0885],
        [-0.0946, -0.0885],
        [-0.0946, -0.0885]], grad_fn=<AddmmBackward0>)

In [15]:
# 定义评价函数
import evaluate

metric = evaluate.load('accuracy')

In [16]:
import numpy as np
from transformers.trainer_utils import EvalPrediction

def compute_metrics(eval_pred):
    logits, labels = eval_pred
    pred = logits.argmax(axis=1)
    # 不用metric, 自己算也行
    # return {'accuracy': (pred == labels).mean()}
    return metric.compute(predictions=pred, references=labels)

# 模拟输出
eval_pred = EvalPrediction(
    predictions=np.array([[0, 1], [2, 3], [4, 5], [6, 7]]),
    label_ids=np.array([1, 1, 0, 1])
)
compute_metrics(eval_pred)

{'accuracy': 0.75}

In [17]:
# 定义训练参数
from transformers import TrainingArguments

In [18]:
args = TrainingArguments(
    # 定义临时数据保存路径
    output_dir='./output_dir',

    # 定义测试执行策略, 可取 no, epoch, steps
    eval_strategy = 'steps',

    # 定义每隔多少个step执行一次测试
    eval_steps = 30,

    # 定义模型保存策略, 可取 no, epoch, steps
    save_strategy = 'steps',

    # 定义每隔多少个step保存一次
    save_steps = 30,

    # 定义总共训练集个轮次
    num_train_epochs = 1,

    # 定义学习率
    learning_rate = 1e-4,

    # 加入参数权重衰减, 防止过拟合
    weight_decay = 1e-2,

    # 定义训练和测试时候的批次大小
    per_device_eval_batch_size = 16,
    per_device_train_batch_size = 16,

    # 定义是否使用GPU训练
    use_cpu = False
 )

In [19]:
# 定义训练器
from transformers import Trainer
from transformers.data.data_collator import DataCollatorWithPadding

In [20]:
trainer = Trainer(
    model = model,
    args = args,
    train_dataset = dataset['train'],
    eval_dataset = dataset['test'],
    compute_metrics = compute_metrics,
    data_collator = DataCollatorWithPadding(tokenizer)
)

In [21]:
# 测试数据整理函数
data_collator = DataCollatorWithPadding(tokenizer)

In [23]:
# 获取一批数据
data = dataset['train'][:5]
print(data)

{'label': [0, 0, 1, 0, 1], 'input_ids': [[101, 1157, 4692, 2130, 8024, 6230, 2533, 2523, 671, 5663, 8024, 3766, 3300, 792, 5305, 784, 720, 2523, 3300, 817, 966, 4638, 5466, 1767, 6226, 1156, 511, 1372, 5543, 6432, 2523, 671, 5663, 4638, 741, 8024, 2130, 1059, 7479, 4143, 868, 1139, 3341, 4638, 511, 102], [101, 1355, 4178, 2661, 782, 8024, 2215, 1071, 3221, 1909, 1921, 4310, 1963, 671, 702, 4125, 3352, 8013, 1100, 1921, 6963, 1377, 809, 4689, 1343, 3265, 2797, 1901, 4638, 7178, 749, 511, 7946, 5682, 2218, 3221, 2900, 5292, 3119, 7415, 1690, 8024, 1506, 102], [101, 6821, 3221, 2769, 743, 4638, 5018, 671, 702, 3315, 3315, 8024, 1333, 3315, 2682, 2137, 691, 5698, 4638, 8024, 852, 3221, 3766, 3300, 6573, 8024, 6821, 3621, 2160, 2242, 4638, 2523, 4023, 778, 8024, 2802, 2458, 4692, 1168, 679, 3221, 5283, 7946, 4638, 8024, 3221, 3300, 4157, 3918, 4149, 5905, 4638, 8024, 2523, 1599, 3614, 511, 6163, 8766, 3683, 6772, 7937, 4172, 8024, 2462, 749, 671, 1288, 5905, 2242, 749, 8024, 738, 3766, 3300, 3227, 4850, 1146, 1277, 2990, 4850, 8024, 6820, 3221, 1486, 6418, 749, 2145, 2787, 2798, 3018, 2137, 749, 511, 1692, 7509, 2523, 2207, 8024, 679, 7231, 8024, 7509, 6574, 738, 1962, 511, 102], [101, 1184, 1378, 3302, 1218, 2345, 8024, 2215, 1071, 3221, 1057, 857, 3198, 2970, 2521, 2769, 4638, 6929, 855, 8024, 4511, 2595, 8024, 1749, 5567, 8024, 2785, 4706, 7262, 511, 1369, 1912, 8024, 2769, 2400, 3766, 3300, 6224, 2791, 7313, 7027, 3300, 3614, 6816, 3362, 4669, 511, 7623, 1324, 7649, 5831, 3717, 2398, 6772, 2345, 511, 817, 3419, 6586, 510, 3302, 1218, 2345, 8024, 4692, 3416, 2094, 4696, 4638, 679, 5543, 857, 749, 511, 102], [101, 1912, 6225, 4023, 778, 8024, 2523, 1377, 4263, 8024, 6844, 1394, 1957, 2111, 2094, 886, 4500, 8024, 5445, 684, 6981, 5390, 2523, 7770, 8024, 1159, 3635, 860, 7741, 2697, 6230, 2523, 5653, 3302, 8024, 6862, 2428, 2523, 2571, 8013, 7241, 4669, 6239, 3043, 3352, 738, 2523, 1962, 8024, 3043, 4708, 2218, 2697, 6230, 5653, 3302, 8013, 102]], 'token_type_ids': [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], 'attention_mask': [[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]]}

In [24]:
# 查看句子长度
for i in data['input_ids']:
    print(len(i))

46
44
108
75
58

In [25]:
# 调用数据整理函数, 进行整理
data = data_collator(data)

In [26]:
# 查看整理之后的数据
for k, v in data.items():
    print(k, v.shape)

input_ids torch.Size([5, 108])
token_type_ids torch.Size([5, 108])
attention_mask torch.Size([5, 108])
labels torch.Size([5])

In [27]:
data

{'input_ids': tensor([[ 101, 1157, 4692, 2130, 8024, 6230, 2533, 2523,  671, 5663, 8024, 3766,
         3300,  792, 5305,  784,  720, 2523, 3300,  817,  966, 4638, 5466, 1767,
         6226, 1156,  511, 1372, 5543, 6432, 2523,  671, 5663, 4638,  741, 8024,
         2130, 1059, 7479, 4143,  868, 1139, 3341, 4638,  511,  102,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0],
        [ 101, 1355, 4178, 2661,  782, 8024, 2215, 1071, 3221, 1909, 1921, 4310,
         1963,  671,  702, 4125, 3352, 8013, 1100, 1921, 6963, 1377,  809, 4689,
         1343, 3265, 2797, 1901, 4638, 7178,  749,  511, 7946, 5682, 2218, 3221,
         2900, 5292, 3119, 7415, 1690, 8024, 1506,  102,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0],
        [ 101, 6821, 3221, 2769,  743, 4638, 5018,  671,  702, 3315, 3315, 8024,
         1333, 3315, 2682, 2137,  691, 5698, 4638, 8024,  852, 3221, 3766, 3300,
         6573, 8024, 6821, 3621, 2160, 2242, 4638, 2523, 4023,  778, 8024, 2802,
         2458, 4692, 1168,  679, 3221, 5283, 7946, 4638, 8024, 3221, 3300, 4157,
         3918, 4149, 5905, 4638, 8024, 2523, 1599, 3614,  511, 6163, 8766, 3683,
         6772, 7937, 4172, 8024, 2462,  749,  671, 1288, 5905, 2242,  749, 8024,
          738, 3766, 3300, 3227, 4850, 1146, 1277, 2990, 4850, 8024, 6820, 3221,
         1486, 6418,  749, 2145, 2787, 2798, 3018, 2137,  749,  511, 1692, 7509,
         2523, 2207, 8024,  679, 7231, 8024, 7509, 6574,  738, 1962,  511,  102],
        [ 101, 1184, 1378, 3302, 1218, 2345, 8024, 2215, 1071, 3221, 1057,  857,
         3198, 2970, 2521, 2769, 4638, 6929,  855, 8024, 4511, 2595, 8024, 1749,
         5567, 8024, 2785, 4706, 7262,  511, 1369, 1912, 8024, 2769, 2400, 3766,
         3300, 6224, 2791, 7313, 7027, 3300, 3614, 6816, 3362, 4669,  511, 7623,
         1324, 7649, 5831, 3717, 2398, 6772, 2345,  511,  817, 3419, 6586,  510,
         3302, 1218, 2345, 8024, 4692, 3416, 2094, 4696, 4638,  679, 5543,  857,
          749,  511,  102,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0],
        [ 101, 1912, 6225, 4023,  778, 8024, 2523, 1377, 4263, 8024, 6844, 1394,
         1957, 2111, 2094,  886, 4500, 8024, 5445,  684, 6981, 5390, 2523, 7770,
         8024, 1159, 3635,  860, 7741, 2697, 6230, 2523, 5653, 3302, 8024, 6862,
         2428, 2523, 2571, 8013, 7241, 4669, 6239, 3043, 3352,  738, 2523, 1962,
         8024, 3043, 4708, 2218, 2697, 6230, 5653, 3302, 8013,  102,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]), 'labels': tensor([0, 0, 1, 0, 1])}

In [28]:
tokenizer.decode(data['input_ids'][0])

'[CLS] 刚 看 完 ， 觉 得 很 一 般 ， 没 有 介 绍 什 么 很 有 价 值 的 职 场 规 则 。 只 能 说 很 一 般 的 书 ， 完 全 靠 炒 作 出 来 的 。 [SEP] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD]'

In [29]:
# 训练和测试

# 测试一把
trainer.evaluate()

{'eval_loss': 0.8028373122215271, 'eval_accuracy': 0.5102040816326531}

In [30]:
# 训练
trainer.train()

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

TrainOutput(global_step=124, training_loss=0.44858289534045803, metrics={'train_runtime': 105.0895, 'train_samples_per_second': 18.851, 'train_steps_per_second': 1.18, 'total_flos': 71338102993548.0, 'train_loss': 0.44858289534045803, 'epoch': 1.0})

In [31]:
trainer.evaluate()

{'eval_loss': 0.18488094210624695, 'eval_accuracy': 0.9285714285714286}

In [32]:
# 保存和加载模型
import torch

In [33]:
trainer.save_model(output_dir='./output_dir/save_model')

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

In [40]:
# 加载 模型

# model.load_state_dict(torch.load('./output_dir/save_model/model.safetensors',map_location=lambda storage, loc: storage.cuda(1),weights_only=True))
from safetensors.torch import load_file

# 1. 使用专用的 load_file 函数
# 2. 注意：你的笔记本通常只有一块显卡，建议将 cuda(1) 改为 cuda(0)
state_dict = load_file('./output_dir/save_model/model.safetensors', device='cuda:0')

# 3. 加载到模型中
model.load_state_dict(state_dict)

In [42]:
# 恢复中断训练
trainer.train(resume_from_checkpoint='./output_dir/checkpoint-90')

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

TrainOutput(global_step=124, training_loss=0.10173170797286495, metrics={'train_runtime': 34.0415, 'train_samples_per_second': 58.194, 'train_steps_per_second': 3.643, 'total_flos': 71338102993548.0, 'train_loss': 0.10173170797286495, 'epoch': 1.0})

In [43]:
trainer.evaluate()

{'eval_loss': 0.18488097190856934, 'eval_accuracy': 0.9285714285714286}

In [45]:
# 预测
model.eval()

# 取一批数据做预测
for i, data in enumerate(trainer.get_eval_dataloader()):
    break

for k, v in data.items():
    # 因为model在gpu上训练的. 所以数据也要拷贝到gpu上
    data[k] = v.to('cuda')

# 预测
out = model(**data)
pred = out['logits'].argmax(dim=1)

In [46]:
pred

tensor([1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0], device='cuda:0')

In [49]:
for i in range(16):
    print(tokenizer.decode(data['input_ids'][i], skip_special_tokens=True))
    print('labels=', data['labels'][i].item())
    print('predict=', pred[i].item())

性 价 比 还 是 蛮 高 的 ， 此 本 本 在 本 地 卖 6999 ， 前 台 优 惠 99 元 ， 估 计 找 老 板 便 宜 个 300 ~ 500 就 差 不 多 了 ， 京 东 的 东 东 还 真 的 便 宜 。
labels= 1
predict= 1
啥 也 不 说 了 ， 就 是 便 宜 ， 昨 天 收 到 的 货 ， 质 量 还 不 确 定 ， 今 天 刚 装 了 xp 系 统 ， 这 样 才 像 电 脑 了 ， 用 起 来 很 方 便 。
labels= 1
predict= 0
1. 纯 黑 键 盘 ， 棕 色 外 面 板 ， 银 色 边 框 ， 耐 看 ， 做 工 也 不 错 ！ ~ 2. 奔 双 4200 ， 速 度 快 ， 显 卡 也 还 可 以 ， 能 应 付 主 流 游 戏 ， led 的 屏 幕 相 当 不 错 ， 显 示 效 果 好 ， 亮 度 高 ， 16 ： 9 的 新 宽 屏 幕 还 有 点 不 习 惯 ， 要 几 天 适 应 ！ 3. 发 货 速 度 很 快 ， 我 是 24 号 下 午 付 款 的 ， 收 款 确 认 后 不 到 2 个 小 时 就 发 货 完 毕 ， 效 率 高 ， 这 一 点 值 得 表 扬 ！ 4 ， 客 服 很 耐 心 ， 银 行 转 账 速 度 太 慢 ， 我 很 着 急 ， 他 耐 心 的 给 我 解 释 ！ 直 到 收 款 确 认 ， 谢 谢 那 位 同 志 。
labels= 1
predict= 1
闹 中 取 静, 虽 然 设 施 旧 了 一 点, 但 对 着 黄 浦 江 的 房 间 风 景 很 不 错, 唯 一 洗 澡 的 水 温 还 是 忽 冷 忽 热, 请 再 检 查 一 下, 这 个 问 题 比 较 严 重 的, 特 别 是 小 孩 洗 澡 的 时 候. 服 务 挺 好 的. 宾 馆 反 馈 2008 年 4 月 16 日 ： 首 先 感 谢 您 对 我 酒 店 风 景 和 服 务 的 肯 定, 酒 店 的 水 管 会 进 一 步 的 维 护 和 保 养, 完 善 现 有 硬 件 设 施, 谢 谢!
labels= 1
predict= 1
首 先 ， 交 通 相 对 来 说 ， 非 常 便 利 ， 从 quarry bay 地 铁 站 的 c 出 口 到 酒 店 不 超 过 5 分 钟 。 酒 店 斜 对 面 是 有 轨 电 车 ， 也 非 常 方 便 。 房 间 总 体 不 错 ， 以 前 印 象 中 香 港 酒 店 的 差 印 象 有 所 改 善 。 room service 也 还 可 以 。 性 价 比 不 错 ， 值 得 推 荐 。
labels= 1
predict= 1
部 分 单 词 偏 僻 ， 不 实 用 单 词 串 讲 ， 无 重 点 而 且 介 绍 上 说 本 书 看 完 会 哈 哈 大 笑 实 在 是 有 些 吹 嘘 了 事 实 上 感 觉 硬 邦 邦 的 幽 默 甚 至 是 自 说 自 话 ， 自 得 其 乐 我 一 点 都 笑 不 起 来 反 觉 得 作 者 有 些 幼 稚 和 低 俗 化 的 趋 势 也 或 许 这 就 是 韩 国 的 特 色 之 一 吧 。
labels= 0
predict= 0
质 量 没 问 题 ， 买 来 到 现 在 十 几 天 了 ， 没 什 么 毛 病 出 现 。 正 版 操 作 系 统 、 正 版 杀 毒 软 件 、 正 版 office 软 件 ， 打 算 不 换 系 统 了 ， 就 用 vista 了 ， 运 行 还 不 错 。
labels= 1
predict= 1
不 知 道 携 程 怎 么 跟 酒 店 协 商 的 ， 明 明 连 住 两 晚 248 ， 酒 店 偏 要 收 我 们 同 事 275 ！ 害 的 我 打 电 弧 给 携 程 和 酒 店 协 调 这 个 事 ， 酒 店 说 销 售 部 没 上 班 ， 晕 ， 销 售 部 没 上 班 你 就 别 开 店 了 ！ ！ 虽 然 后 来 在 携 程 的 努 力 下 酒 店 做 出 了 补 偿 性 的 方 案 ， 但 毕 竟 这 样 的 遭 遇 确 实 让 人 很 不 舒 服 。 其 实 我 们 一 般 去 重 庆 都 是 住 这 里 ， 也 没 有 特 别 不 如 意 的 地 方 。 但 是 这 样 看 上 去 酒 店 方 小 小 的 失 误 ， 确 给 消 费 者 非 常 不 舒 服 的 感 觉 ， 我 想 这 事 对 富 丽 来 讲 不 是 偶 然 ， 期 望 富 丽 持 续 改 进 。
labels= 0
predict= 0
预 装 的 vista 系 统 只 给 分 了 两 个 区 太 不 合 理 了 本 来 是 优 点 的 现 在 却 弄 成 了 缺 陷
labels= 0
predict= 0
女 儿 五 年 级 ， 语 文 课 本 里 有 节 选 城 南 旧 事 的 一 篇 课 文 ， 所 以 孩 子 让 我 给 她 买 整 本 书 来 看 。 女 儿 见 过 她 的 同 学 买 的 那 种 ， 插 图 很 精 美 的 书 ， 这 本 书 拿 回 去 后 ， 她 发 现 跟 同 学 的 那 本 不 一 样 ， 但 看 完 以 后 ， 女 儿 告 诉 我 ， 妈 咪 ， 这 本 书 的 插 图 也 很 漂 亮 呢 ！ 是 的 ， 买 书 是 看 内 容 的 ， 精 装 版 和 简 装 版 ， 只 要 是 好 书 ， 其 实 是 一 样 的 。
labels= 1
predict= 1
之 前 买 过 一 次 ， 所 有 书 都 相 当 不 错 这 次 怎 么 这 样 啊 三 本 书 那 质 量 都 ？ ？ ？ 不 过 内 容 不 错 哈
labels= 0
predict= 1
我 住 的 158 的 房, 觉 得 还 可 以, 房 间 正 对 酒 店 大 门 口 的 马 路, 隔 音 还 可 以, 不 吵. 卫 生 间 也 不 是 太 少, 就 是 设 计 不 太 合 理, 洗 澡 的 龙 头 力 道 太 大, 水 打 在 身 上 都 疼. 综 合 来 说 还 可 以.
labels= 1
predict= 0
选 购 的 时 候 ， 还 是 有 货 的 。 最 后 却 通 知 我 说 ， 没 货 了 。 当 当 的 服 务 态 度 ， 实 在 有 待 改 善 。
labels= 0
predict= 0
不 知 大 陆 观 众 有 多 少 看 过 台 湾 的 生 活 智 慧 王 节 目 ， 里 面 介 绍 了 很 多 生 活 技 巧 ， 尤 其 是 居 家 烹 饪 方 面 的 。 这 本 书 专 门 介 绍 了 能 在 较 短 时 间 内 作 出 美 味 不 重 样 而 且 健 康 的 餐 点 的 方 法 技 巧 ， 很 适 合 现 代 社 会 的 忙 碌 一 族 （ 或 者 说 是 懒 人 吧 ） ， 还 有 提 高 烹 饪 效 率 的 一 些 窍 门 。 图 片 很 直 观 ， 文 字 就 简 略 了 些 ， 要 掌 握 技 巧 还 得 多 实 践 啊 ， 比 老 吃 快 餐 或 外 卖 好 多 了 ， 还 能 增 进 跟 家 人 的 感 情 哦 ～
labels= 1
predict= 1
配 置 均 衡 ， 性 能 强 劲 ， 做 工 精 致 ， 散 热 良 好 。 配 件 丰 富 。 其 中 还 有 一 个 dell 原 装 的 鼠 标 垫 。 同 事 很 满 意 。
labels= 1
predict= 1
堂 堂 四 星 级 酒 店 ， 写 错 了 房 号 。 用 户 按 照 订 单 退 的 房 间 ， 给 携 程 反 馈 的 是 提 前 退 房 。 这 种 服 务 能 符 合 四 星 级 吗 ？
labels= 0
predict= 0